version: "3"

services:

  contentum:
    build:
      context: .
    restart: always
    container_name: contentum
    environment:
      - "WORKERS=1"
      - "DEBUG=contentum*"
    ports:
      - "3000:3000"
    networks:
      - contentum-network

networks:
  contentum-network:
