version: "3"

services:

  sssr:
    build:
      context: .
    restart: always
    container_name: sssr
    environment:
      - "WORKERS=1"
      - "DEBUG=sssr*"
    ports:
      - "3000:3000"
    networks:
      - sssr-network

networks:
  sssr-network:
