version: "3.8"

services:

  contentum:
    build:
      context: .
    restart: unless-stopped
    container_name: contentum
    environment:
      - "WORKERS=1"
      - "DEBUG=contentum*"
    ports:
      - "3000:3000"
    networks:
      - contentum-network
    volumes:
      - ./:/app
      - /app/node_modules

networks:
  contentum-network:
    name: "contentum"
    driver: "bridge"
